### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-environment#29]
**Is your feature request related to a problem? Please describe.**
The current version of `senzing-environment` is light on documentation on how to use the artifacts after they are built.  

This issue is to add documentation that will help the user after `docker-bin`, `docker-etc`, and `docker-setupEnv` have been created.

**Comment by docktermj** [comment]
In `docker-environment-vars.sh`,  add a comment about the use (actually non-use) of `localhost` as the value of `localhost` seen inside of containers would be relative to inside the docker container, when the host-ip is what is really needed.

**Comment by docktermj** [comment]
In the `docker-bin` directory, create a ` README.txt` file that points to a documentation page on GitHub that describes each of the shell files in the the directory.

**Comment by kernelsam** [comment]
Closing as will not implement due to deprecation.
