### ISSUE TITLE
Add script to automate cleanup

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-environment#30]
If I wish to remove the senzing-environment assets from my G2CreateProject project I should have a handy script to run instead of having to manually clean up. 

Upon first run that creates the docker-* assets in the project directory  or subsequent runs that creates the timestamped backups create/update shell script to remove them all, e.g, senzing-environment-remove.sh or similar. It shouldn't rely on using rm -rf docker*, it's plausible I could have other assets in the path named so I don't wish to remove. Additionally have the script list assets to be removed and ask user to confirm.

**Comment by kernelsam** [comment]
Closing as will not implement due to deprecation.
