### ISSUE TITLE
Output from starting up to point to (new) documentation on using Swagger locally vs Swagger website

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-environment#43]
Add new documentation and reference it when starting up. The latest senzing-environment when starting - for example - the web app demo outputs:

```
== senzenvtest-webapp running on http://192.168.1.69:8251
== senzenvtest-api-server running on http://192.168.1.69:8250
== Swagger editor: http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api-specification/master/senzing-rest-api.yaml
```

The URL for Swagger points to the external editor for Swagger. This will not work when working in SzUp or senzing-environment due to protocol request change where Swagger external is using https but the REST API server used by the demo app is using http. (Note also the above Swagger editor URL says http but this should be https).

The new swagger-ui.sh that implements a local Swagger container using http to communicate to the REST API server and used for learning and demonstrations is available locally on the host. Using this needs to be documented, the difference between using the external Swagger editor and the local container and link to this documentation output instead of the URL as seen above.

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/senzing-environment/pull/44
2. https://github.com/Senzing/senzing-environment/pull/45
3. https://github.com/Senzing/senzing-environment/pull/46
