### ISSUE TITLE
Show volumes

### ISSUE THREAD

**Issue by ryanbasile** [Senzing/senzing-environment#47]
**Is your feature request related to a problem? Please describe.**
Show volumes

**Describe the solution you'd like**
```
==================================================================================
== View: http://localhost:8251
== Project location: /home/ryan/my-first-senzing-test
==Mountable volume location: <SHOW LOCATION HERE>
==================================================================================
```

**Additional context**
This would be nice to see when running senzing-up

**Comment by docktermj** [comment]
Pull requests:

https://github.com/Senzing/senzing-environment/pull/69
