### ISSUE TITLE
Support Docker Networks

### ISSUE THREAD

**Issue by edykes** [Senzing/senzing-environment#53]
docker network create senzing-network

docker run \
  --detach \
   --name senzing_xterm \
  --network=senzing-network \
  --publish 8254:5000 \
  --restart always \
  --volume ${SENZING_DATA_VERSION_DIR}:/opt/senzing/data \
  --volume ${SENZING_ETC_DIR}:/etc/opt/senzing \
  --volume ${SENZING_G2_DIR}:/opt/senzing/g2 \
  --volume ${SENZING_VAR_DIR}:/var/opt/senzing \
  senzing/xterm

**Comment by docktermj** [comment]
Pull request

1. https://github.com/Senzing/senzing-environment/pull/54
