### ISSUE TITLE
Support docker network based on project name

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-environment#73]
This issue has 2 related parts:

### Docker network name

Use the project name (a.k.a directory name) as the name of the docker network.  This will allow separate versions of Senzing Up to run concurrently. (if ports differ)

### Shell script make sure network is up

Although the docker network may already be up,  there are conditions where it may not be up (i.e.deleted by user).  Add code in each `senzing-*.sh` to make sure the docker network has been created.

**Comment by kernelsam** [comment]
Closing as will not implement due to deprecation.
