### ISSUE TITLE
Use SENZING_RABBITMQ_USE_EXISTING_ENTITIES

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-environment#74]
Add

```console
    --env SENZING_RABBITMQ_USE_EXISTING_ENTITIES="False"
```

where appropriate.  Such as:

1. `senzing/stream-loader`
2. `senzing/stream-producer`
3. `senzing/redoer`
4. `senzing/stream-logger`

**Comment by kernelsam** [comment]
Closing as will not implement due to deprecation.
