### ISSUE TITLE
Message dictionary reusing the same key for different messsages

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-environment#81]
The message_dictionary specifies 173 twice, first one should be 152?

**Comment by docktermj** [comment]
Yes,

https://github.com/Senzing/senzing-environment/blob/aaf45fe8c363b5add00651d15e82b846dd80da49/senzing-environment.py#L220

should be:

```python
 "152": "{0} - Changing owner from {1} to {2}",
```
